### ISSUE TITLE
Task: Plugin scraping automation

### ISSUE THREAD

**Issue by CakeCrusher** [CakeCrusher/openplugin#15]
## Chat
https://chat.openai.com/share/6c356c82-3607-4c92-8271-99144239b1ae
## Description
Formerly I could use the devtools "network" tab to copy the all of the 100s of plugins' data and paste it in [`openai_res.json`](https://github.com/CakeCrusher/openplugin/blob/main/migrations/plugin_store/openai_res.json). Since, OpenAI has introduced server-side which results in only the batches being accessible at a time as demonstrated below.

![Image](https://github.com/CakeCrusher/openplugin/assets/37946988/870b84f6-1162-412e-bf61-cafa22147986)

The goal of this task is so that once `Plugin store` is open I should be able to insert a script that will:

1. click on `All` button 
3. navigate through all of the pages 
4. composes a single list containing all of the plugins' information that should be of shape as the items in `openai_res.json`. 

Worst case scenario I should at least be able to extract the fields shown [here](https://github.com/CakeCrusher/openplugin/blob/e7abbbbed8ce2d52d4a1b448070a4aa54238c6dd/migrations/plugin_store/openplugins_info.json#L3-L9)

## Tasks
These tasks are set up to be used as part of the ChatGPT prompts along with any additional context required. They don't need to be strictly followed but it is encouraged to use them as a guide.
- [x] Enable plugins https://www.youtube.com/watch?v=Ad5yoGcTW_o
- [x] Programmatically click on the `All` button
- [x] Identify where the data for the plugin `items` is being requested on first load
- [x] Identify where the data for the rest of the plugin `items` is being requested as you navigate through the paginated plugins. The image below demonstrates that every time you navigate to a new plugin page a new (or it may be a long-lived connection) `approved?...` request is made

![Image](https://github.com/CakeCrusher/openplugin/assets/37946988/dd92644d-cbb1-4829-8450-6173e4851b7a)

- [x] Be able to extract/intercept the data from the requests
- [x] Automate the navigation through the plugin pages so as to get all the plugin information from the 1st page to the final page
- [x] Concatenate that data so that it has the same structure as `openai_res.json`
- [x] Ensure that all the aforementioned tasks run as a single seamless script
- [x] PR this script in `migrations/plugin_store/scrape_plugins_script.js`
