### ISSUE TITLE
Task: Fix langchain JSON parsing issue

### ISSUE THREAD

**Issue by CakeCrusher** [CakeCrusher/openplugin#19]
## Chat
https://chat.openai.com/share/cdf181c2-798a-4cd6-95e5-5e3ab70fb04d
## Description
Currently there are certain plugins that raise a JSON parse error. Resolve this error.
## Tasks
- [x] Get a working fork of `langchain` that you can confidently develop on called, publish it to `oplangchain`
- [x] Identify plugins with that problem by creating a `test/unrestricted-plugin-access` branch in openplugin.io and eliminating holds "unsupported" plugins.
- [x] Create a test that is a copy of `openplugin.fetch_plugin` on the `langchain` fork
- [x] Debug that test
  - [x] The root url is wrong
  - [ ] The attributes method is missassigned (what should be `params` is assigned `json`)
- [x] Validate that changes are not breaking "supported" plugins
- [x] Publish new version of `oplangchain`
- [x] Update `openplugincore` dependencies
- [x] Make sure `openplugin-api` is using updated `openplugin`
- [x] Modify `test/unrestricted-plugin-access` to not add to the usage count
- [x] Uprate must be implemented to then uprate solved plugins

**Comment by CakeCrusher** [comment]
resolved by #22
